//===--- PrinssharedmemoryusageCheck.h - clang-tidy--------------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_BTC_PRINSSHAREDMEMORYUSAGECHECK_H
#define LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_BTC_PRINSSHAREDMEMORYUSAGECHECK_H

#include "../ClangTidy.h"

namespace clang {
namespace tidy {
namespace btc {

/// FIXME: Write a short description.
///
/// For the user-facing documentation see:
/// http://clang.llvm.org/extra/clang-tidy/checks/btc-PRINSSharedMemoryUsage.html
class PrinssharedmemoryusageCheck : public ClangTidyCheck {

  struct PsmInfo {
    std::string PSMName;
    std::vector<std::string> StructTypes;
  };

  std::map<int, PsmInfo> PsmMap{{0, {"MELD_PSM", {"MEPSM"}}},
                                {1, {"MESS_PSM", {"MWPSM"}}},
                                {2, {"SOLL_PSM", {"SWPSM"}}},
                                {3, {"ZAEL_PSM", {"ZWPSM"}}},
                                {4, {"AMESS_PSM", {"AMWPSM"}}},
                                {5, {"AMELD_PSM", {"AMEPSM"}}},
                                {6, {"AZAEL_PSM", {"AZWPSM"}}},
                                {7, {"HSTSTAT_PSM", {"HSTPSM"}}},
                                {8, {"DTG_PSM", {"DTG_HEADER","DTG_SEND"}}},
                                {9, {"TOPPVROHRABS_S_PSM", {}}},
                                {10, {"TOPROHRABS_D_PSM", {"TOPROHRABS_D"}}},
                                {11, {"TOPROHRABS_S_PSM", {}}},
                                {12, {"TOPROHRABS_SR_PSM", {}}},
                                {13, {"WERSTU_PSM", {}}}, // Is not typed
                                {19, {"ERGRING_PSM", {"ERGHEAD_SM", "ERGDAT", "STSBYTE"}}}, 
                                {20, {"ZEICOM_PSM", {"STS_DATETIME"}}},
                                {21, {"TOPELE_PSM", {"TEPSM"}}},
                                {22, {"MELDFWA_PSM", {"FWA"}}},
                                {23, {"MESSFWA_PSM", {"FWA"}}},
                                {24, {"SOLLFWA_PSM", {"FWA"}}},
                                {25, {"ZAELFWA_PSM", {"FWA"}}},
                                {26, {"BEFFWA_PSM", {"FWA"}}},
                                {27, {"TSTSTAT_PSM", {"TSTPSM"}}},
                                {28, {"KENNL_PSM", {"KLPSM"}}},
                                {29, {"TRAFO_PSM", {"TRSPSM"}}},
                                {30, {"TRAFOFWA_PSM", {"FWA"}}},
                                {31, {"SYSTEMPV_PSM", {"SYSPVPSM"}}},
                                {32, {"SOPTO_PSM", {"<NOTYPE>"}}}, // Is not typed
                                {33, {"VERBINDUNGDAT_PSM", {"VERBINDUNG"}}},
                                {34, {"ALKOM_PSM", {"ALKOMPSM"}}},
                                {35, {"MESSVOR_PSM", {"MWVORPSM"}}},
                                {36, {"ZWEMENGE_PSM", {"ZWEMENGE"}}},
                                {37, {"VFGPRINS_PSM", {"VFGPRINS"}}},
                                {38, {"BEF_PSM", {"BEFPSM"}}},
                                {39, {"FLD_PSM", {"FLDPSM"}}},
                                {40, {"MEFLD_PSM", {"SATZNR"}}},
                                {41, {"MWFLD_PSM", {"SATZNR"}}},
                                {42, {"TRSFLD_PSM", {"SATZNR"}}},
                                {43, {"ZWFLD_PSM", {"SATZNR"}}},
                                {44, {"BEFFLD_PSM", {"SATZNR"}}},
                                {45, {"SWFLD_PSM", {"SATZNR"}}},
                                {46, {"ANL_PSM", {"ANLPSM"}}},
                                {47, {"AMEBRF_PSM", {"SATZNR"}}},
                                {48, {"AMWAZWBRF_PSM", {"BRF_NODE"}}},
                                {49, {"BERTEILGDAT_PSM", {"BEREICHS_TEILUNG"}}},
                                {50, {"TSTSAM_PSM", {"TSTPSM"}}},
                                {51, {"HSTSAM_PSM", {"HST_SAMMELSTOER"}}},
                                {52, {"FLDSAM_PSM", {"FLD_SAMMELSTOER"}}},
                                {53, {"WMWVFOS_PSM", {}}}, // Is not typed
                                {59, {"MESSGW_PSM", {"MESSGW_SATZ"}}},
                                {60, {"AMESSGW_PSM", {"AMESSGW_SATZ"}}},
                                {61, {"SOPTOMESS_PSM", {"SOPTOMWPSM"}}},
                                {62, {"TOPANSCHLUSS_S_PSM", {}}},
                                {63, {"TOPVKNOT_S_PSM", {}}},
                                {64, {"TOPBEL_S_PSM", {}}},
                                {65, {"TOPSTATION_S_PSM", {}}},
                                {66, {"TOPPVSTATION_S_PSM", {}}},
                                {67, {"TOPSTATION_SR_PSM", {}}},
                                {68, {"MESS_LZA1_PSM", {}}},
                                {74, {"MESS_WVA1_PSM", {}}},
                                {80, {"TOPSTATION_D_PSM", {}}},
                                {81, {"UMS_PSM", {"UMSPSM"}}},
                                {82, {"SIM_UMS_PSM", {}}},
                                {83, {"ARCHIV_PSM", {}}},
                                {83, {"LZA1_PSM", {"LZAPSM"}}},
                                {84, {"LZA2_PSM", {}}},
                                {85, {"LZA3_PSM", {}}},
                                {86, {"LZA4_PSM", {}}},
                                {87, {"LZA5_PSM", {}}},
                                {88, {"LZA6_PSM", {}}},
                                {89, {"WVA1_PSM", {}}},
                                {90, {"WVA2_PSM", {}}},
                                {91, {"WVA3_PSM", {}}},
                                {92, {"WVA4_PSM", {}}},
                                {93, {"WVA5_PSM", {}}},
                                {94, {"WVA6_PSM", {}}},
                                {95, {"MELDPROJ_PSM", {}}},
                                {96, {"MESSPROJ_PSM", {}}},
                                {97, {"TRAFOPROJ_PSM", {}}},
                                {98, {"ZAELPROJ_PSM", {}}},
                                {99, {"BEFPROJ_PSM", {}}},
                                {100, {"SOLLPROJ_PSM", {}}},
                                {101, {"TEM_PSM", {"TEMPSM"}}},
                                {102, {"HSTVER_PSM", {"VERRBED"}}},
                                {103, {"SHALIKOM_PSM", {"UPDATE_SLU_UK48"}}},
                                {104, {"LTGABSDAT_PSM", {"LTG_ABSCHNITT"}}},
                                {105, {"MELDDIAPRF_PSM", {"PRF_MEPSM","MEPSM"}}},
                                {106, {"MESSDIAPRF_PSM", {"PRF_MWPSM","MWPSM"}}},
                                {107, {"TRAFODIAPRF_PSM", {"PRF_TRSPSM","TRSPSM"}}},
                                {108, {"ZAELDIAPRF_PSM", {"PRF_ZWPSM","ZWPSM"}}},
                                {109, {"BEFDIAPRF_PSM", {"PRF_BEFPSM"}}},
                                {110, {"SOLLDIAPRF_PSM", {"PRF_SWPSM"}}},
                                {111, {"ZAELARCHIV_PSM", {"ZWARCHIVPSM"}}}, //??
                                {112, {"ZAELBRENN_PSM", {"ZWBRENNPSM"}}},
                                {113, {"ZAELBRENNPRF_PSM", {"ZWBRENNPSM"}}},
                                {114, {"ZAEL2_PSM", {"ZW2PSM"}}},
                                {115, {"TEILNETZ_PSM", {}}},
                                {116, {"MELDDAT_PSM", {"MELD"}}},
                                {117, {"MESSDAT_PSM", {"MESS"}}},
                                {118, {"TRAFODAT_PSM", {"TRAFO"}}},
                                {119, {"ZAELDAT_PSM", {"ZAEL"}}},
                                {120, {"BEFDAT_PSM", {"BEF"}}},
                                {121, {"SOLLDAT_PSM", {"SOLL"}}},
                                {122, {"AMELDDAT_PSM", {"AMELD"}}},
                                {123, {"AMESSDAT_PSM", {"AMESS"}}},
                                {124, {"AZAELDAT_PSM", {"AZAEL"}}},
                                {125, {"STAT_PSM", {"STATPSM"}}},
                                {126, {"STATSSM_PSM", {"TSTPSM"}}},
                                {127, {"STATSAM_PSM", {"TSTPSM"}}},
                                {128, {"STATSSM_ALR_PSM", {"TSTALRPSM"}}},
                                {129, {"STATSAM_ALR_PSM", {"TSTALRPSM"}}},
                                {130, {"SIM_STAT_PSM", {}}},
                                {131, {"TOP_DSTATPSM", {}}},
                                {132, {"TOP_DUMSPSM", {}}},
                                {133, {"ZAELDYN_PSM", {"ZAELDYN"}}},
                                {134, {"ROHMELD_PSM", {"ROHMELDPSM"}}},
                                {135, {"ROHMESS_PSM", {"ROHMESSPSM"}}},
                                {136, {"ROHZAEL_PSM", {"ROHZAELPSM"}}},
                                {137, {"ROHTRAFO_PSM", {"ROHTRAFOPSM"}}},
                                {138, {"LTGABS_PSM", {"LTGABSPSM"}}},
                                {139, {"FLDTE_PSM", {"FLDTEPSM","FLDTE"}}},
                                {140, {"TOPTRAFO_M_PSM", {}}},
                                {141, {"MW_KORR_MW_PSM", {"MW_KORR_MW"}}},
                                {142, {"MW_SCHWELL_PSM", {"MWSCHWPSM"}}},
                                {143, {"AMESSVOR_PSM", {"MWVORPSM"}}},
                                {144, {"NETZK_PSM", {"NETZKPSM"}}},
                                {145, {"LTG_PSM", {"LTGPSM"}}},
                                {146, {"METOP_PSM", {"METOPPSM","MELDTOP"}}},
                                {147, {"AMETOP_PSM", {"AMETOPPSM","AMELDTOP"}}},
                                {148, {"ZAELERW_PSM", {"ZAELERW"}}},
                                {149, {"ZAELVORGABE_PSM", {"ZWVORGABEPSM"}}},
                                {150, {"SIM_STATDAT_PSM", {}}},
                                {151, {"IWERSTU_PSM", {}}}, // Is not typed
                                {157, {"IMWVFOS_PSM", {}}}, // Is not typed
                                {163, {"AZWCARRY_PSM", {"ZWCARRYPSM"}}},
                                {164, {"TOPANLAGE_D_PSM", {}}},
                                {165, {"TOPANLAGE_P_PSM", {}}},
                                {166, {"TOPANLAGE_S_PSM", {}}},
                                {167, {"TOPELEMENT_G_PSM", {}}},
                                {168, {"TOPMEL_SN_PSM", {}}},
                                {169, {"TOPELEMENT_D_PSM", {}}},
                                {170, {"TOPELEMENT_N_PSM", {}}},
                                {171, {"TOPELEMENT_S_PSM", {}}},
                                {172, {"TOPELEMENT_T_PSM", {}}},
                                {173, {"TOPESPULE_D_PSM", {}}},
                                {174, {"TOPESPULE_S_PSM", {}}},
                                {175, {"TOPFELD_C_PSM", {}}},
                                {176, {"TOPFELD_D_PSM", {}}},
                                {177, {"TOPFELD_N_PSM", {}}},
                                {178, {"TOPFELD_P_PSM", {}}},
                                {179, {"TOPFELD_S_PSM", {}}},
                                {180, {"TOPFELD_T_PSM", {}}},
                                {181, {"TOPGRUPPE_D_PSM", {}}},
                                {182, {"TOPINETZ_D_PSM", {}}},
                                {183, {"TOPKNOT_D_PSM", {}}},
                                {184, {"TOPKNOT_K_PSM", {}}},
                                {185, {"TOPKNOT_S_PSM", {}}},
                                {186, {"TOPLAST_D_PSM", {}}},
                                {187, {"TOPLAST_S_PSM", {}}},
                                {188, {"TOPLEIT_D_PSM", {}}},
                                {189, {"TOPLEIT_S_PSM", {}}},
                                {190, {"TOPLEITELEMENT_K_PSM", {}}},
                                {191, {"TOPLEITELEMENT_N_PSM", {}}},
                                {192, {"TOPLEITELEMENT_S_PSM", {}}},
                                {193, {"TOPLTGABS_D_PSM", {}}},
                                {194, {"TOPLTGABS_S_PSM", {}}},
                                {195, {"TOPMEL_D_PSM", {}}},
                                {196, {"VOSME_PVS_PSM", {"VOSME_PV_DATA"}}},
                                {197, {"TOPMEL_S_PSM", {}}},
                                {198, {"TOPMEL_V_PSM", {}}},
                                {199, {"TOPMES_D_PSM", {}}},
                                {200, {"TOPMES_S_PSM", {}}},
                                {201, {"TOPNETZ_D_PSM", {}}},
                                {202, {"TOPNETZ_S_PSM", {}}},
                                {203, {"TOPPVAMEL_S_PSM", {}}},
                                {204, {"TOPPVAMES_S_PSM", {}}},
                                {205, {"TOPPVANLA_S_PSM", {}}},
                                {206, {"TOP_TMEPSM", {}}},
                                {207, {"TOPPVEIN_S_PSM", {}}},
                                {208, {"TOPPVELEM_S_PSM", {}}},
                                {209, {"TOPPVFELD_S_PSM", {}}},
                                {210, {"TOP_DMWPSM", {}}},
                                {211, {"TOPPVKNOT_S_PSM", {}}},
                                {212, {"TOPPVLAST_S_PSM", {}}},
                                {213, {"TOPPVLEIT_S_PSM", {}}},
                                {214, {"TOPPVLTGABS_S_PSM", {}}},
                                {215, {"TOPPVMEL_S_PSM", {}}},
                                {216, {"TOP_DTEMPSM", {}}},
                                {217, {"TOPPVMES_S_PSM", {}}},
                                {218, {"TOPPVUMS_S_PSM", {}}},
                                {219, {"TOPSTATTNETZ_D_PSM", {}}},
                                {220, {"TOPSTATTNETZ_N_PSM", {}}},
                                {221, {"TOPSTATTNETZ_S_PSM", {}}},
                                {222, {"TOPTNETZ_D_PSM", {}}},
                                {223, {"TOPTNETZ_K_PSM", {}}},
                                {224, {"TOPTRAFO_D_PSM", {}}},
                                {225, {"TOPTRAFO_N_PSM", {}}},
                                {226, {"TOPTRAFO_S_PSM", {}}},
                                {227, {"TOPVERSORG_D_PSM", {}}},
                                {228, {"TOPVERSORG_S_PSM", {}}},
                                {229, {"ALUME_PVS_PSM", {"ALUME_PV_DATA"}}},
                                {230, {"FLDDYNMARK_PSM", {"FLDDYNMARKPSM"}}},
                                {231, {"TOPENERGIEUW_S_PSM", {}}},
                                {239, {"TOPAMEL_SR_PSM", {}}},
                                {240, {"TOPAMES_SR_PSM", {}}},
                                {241, {"TOPANLAGE_SR_PSM", {}}},
                                {242, {"TOPELEM_SR_PSM", {}}},
                                {243, {"TOPESPULE_SR_PSM", {}}},
                                {244, {"TOPFELD_SR_PSM", {}}},
                                {245, {"TOPGEN_SR_PSM", {}}},
                                {246, {"TOPLAST_SN_PSM", {}}},
                                {247, {"TOPLAST_SR_PSM", {}}},
                                {248, {"TOPLEITELEM_SN_PSM", {}}},
                                {249, {"TOPLEITELEM_SR_PSM", {}}},
                                {250, {"TOPLEIT_SR_PSM", {}}},
                                {251, {"TOPLTGABS_SR_PSM", {}}},
                                {252, {"TOPMEL_SR_PSM", {}}},
                                {253, {"TOPMES_SR_PSM", {}}},
                                {254, {"TOP_DAMEPSM", {}}},
                                {255, {"TOP_DAMWPSM", {}}},
                                {256, {"TOP_DTRSPSM", {}}},
                                {257, {"TOPTNETZ_SR_PSM", {}}},
                                {258, {"TOPTRAFO_SN_PSM", {}}},
                                {259, {"TOPTRAFO_SR_PSM", {}}},
                                {260, {"TOPVERSORG_SN_PSM", {}}},
                                {261, {"TOPVERSORG_SR_PSM", {}}},
                                {262, {"TRAIN_AMESS_PSM", {}}},
                                {263, {"TRAIN_ANL_PSM", {}}},
                                {264, {"TRAIN_FLD_PSM", {}}},
                                {265, {"TRAIN_LTG_PSM", {}}},
                                {266, {"TRAIN_LTGABS_PSM", {}}},
                                {267, {"TRAIN_MELD_PSM", {}}},
                                {268, {"TRAIN_MESS_PSM", {}}},
                                {269, {"TOP_FLDMOD_PSM", {}}},
                                {270, {"TOP_FLDDAT_PSM", {}}},
                                {271, {"TOP_DANLPSM", {}}},
                                {272, {"TRAIN_TE_PSM", {}}},
                                {273, {"TRAIN_TEM_PSM", {}}},
                                {274, {"TOPWTAUSCHER_D_PSM", {}}},
                                {275, {"TOPWTAUSCHER_S_PSM", {}}},
                                {276, {"TOPWTAUSCHER_SR_PSM", {}}},
                                {277, {"PBTRSTDAT_PSM", {"PBTRST"}}},
                                {278, {"METEXTME_PSM", {"METEXTMEPSM"}}},
                                {279, {"TOPUMWAELZ_D_PSM", {}}},
                                {280, {"TSTSTAT_ALR_PSM", {"TSTALRPSM"}}},
                                {281, {"TSTSAM_ALR_PSM", {"TSTALRPSM"}}},
                                {282, {"SIM_AMEBRF_PSM", {}}},
                                {283, {"SIM_AMEDAT_PSM", {}}},
                                {284, {"SIM_AME_PSM", {}}},
                                {285, {"SIM_AMW_PSM", {}}},
                                {286, {"SIM_ANLDAT_PSM", {}}},
                                {287, {"SIM_ANL_PSM", {}}},
                                {288, {"SIM_AZW_PSM", {}}},
                                {289, {"SIM_BEFFLD_PSM", {}}},
                                {290, {"SIM_BEFFWA_PSM", {}}},
                                {291, {"SIM_BEFPROJ_PSM", {}}},
                                {292, {"SIM_BEF_PSM", {}}},
                                {293, {"SIM_BEFRME_PSM", {}}},
                                {294, {"SIM_FLDDAT_PSM", {}}},
                                {295, {"SIM_FLD_PSM", {}}},
                                {296, {"SIM_HST_PSM", {}}},
                                {297, {"SIM_LTGABS_PSM", {}}},
                                {298, {"SIM_LTG_PSM", {}}},
                                {299, {"SIM_MEFLD_PSM", {}}},
                                {300, {"SIM_MEFWA_PSM", {}}},
                                {301, {"SIM_MEPROJ_PSM", {}}},
                                {302, {"SIM_ME_PSM", {}}},
                                {303, {"SIM_MWFLD_PSM", {}}},
                                {304, {"SIM_MWFWA_PSM", {}}},
                                {305, {"SIM_MWPROJ_PSM", {}}},
                                {306, {"SIM_MW_PSM", {}}},
                                {307, {"TRAIN_TRS_PSM", {}}},
                                {308, {"SIM_AMWAZWBRF_PSM", {}}},
                                {309, {"SIM_AMWDAT_PSM", {}}},
                                {310, {"SIM_SWFLD_PSM", {}}},
                                {311, {"SIM_SWFWA_PSM", {}}},
                                {312, {"SIM_SWPROJ_PSM", {}}},
                                {313, {"SIM_SW_PSM", {}}},
                                {314, {"SIM_TEM_PSM", {}}},
                                {315, {"SIM_TE_PSM", {}}},
                                {316, {"SIM_TRSFLD_PSM", {}}},
                                {317, {"SIM_TRSFWA_PSM", {}}},
                                {318, {"SIM_TRSPROJ_PSM", {}}},
                                {319, {"SIM_TRS_PSM", {}}},
                                {320, {"TOPPVSTATTNETZ_S_PSM", {}}},
                                {321, {"SIM_ZWFLD_PSM", {}}},
                                {322, {"SIM_ZWFWA_PSM", {}}},
                                {323, {"SIM_ZWPROJ_PSM", {}}},
                                {324, {"SIM_ZW_PSM", {}}},
                                {325, {"SIM_RESOURCES", {}}},
                                {326, {"NETZS_PSM", {"NETZSPSM"}}},
                                {327, {"TOPNETZS_D_PSM", {}}},
                                {328, {"TOPNETZS_S_PSM", {}}},
                                {329, {"TOPNETZS_SR_PSM", {}}},
                                {330, {"TOPPVNETZS_S_PSM", {}}},
                                {331, {"TNDST_PSM", {"TNDSTPSM"}}},
                                {332, {"AMEFLD_PSM", {"SATZNR"}}},
                                {333, {"AMWFLD_PSM", {"SATZNR"}}}, //TODO oder AMWPSM?
                                {334, {"AZWFLD_PSM", {"SATZNR"}}}, //TODO oder AZWPSM ?
                                {335, {"FLDTNETZ_PSM", {"SATZNR"}}},
                                {336, {"TNSSM_PSM", {"TSTPSM"}}},
                                {337, {"TNSSM_PAR_PSM", {"TSTPSM"}}},
                                {338, {"TNSSM_ALR_PSM", {"TSTALRPSM"}}},
                                {339, {"TNSSM_PAR_ALR_PSM", {"TSTALRPSM"}}},
                                {340, {"TOPMEL_SV_PSM", {}}},
                                {341, {"TOPPVWTAUSCHER_S_PSM", {}}},
                                {342, {"TNETZINF_DAT_PSM", {}}},
                                {343, {"TNETZINF_NAM_PSM", {}}},
                                {344, {"SIM_AZWDAT_PSM", {}}},
                                {346, {"TOPKNOT_SR_PSM", {}}},
                                {347, {"TOPPVESPULE_S_PSM", {}}},
                                {348, {"TOPPVLEITELEMENT_S_PSM", {}}},
                                {349, {"TOPTNETZ_DAT_PSM", {"SATZNR"}}},
                                {350, {"NET_RAMSEM_PSM", {}}},
                                {351, {"NETAUSFALL_PSM", {}}},
                                {352, {"NETRECHNUNG_PSM", {}}},
                                {353, {"NETKNOTEN_D_PSM", {}}},
                                {354, {"NETKNOTEN_E_PSM", {}}},
                                {355, {"NETKNOTEN_K_PSM", {}}},
                                {356, {"NETZWEIG_A_PSM", {}}},
                                {357, {"NETZWEIG_B_PSM", {}}},
                                {358, {"NETZWEIG_D_PSM", {}}},
                                {359, {"NETZWEIG_E_PSM", {}}},
                                {360, {"NETZWEIG_F_PSM", {}}},
                                {361, {"NETZWEIG_K_PSM", {}}},
                                {362, {"NETZWEIG_S_PSM", {}}},
                                {363, {"NETZWEIGLIS_D_PSM", {}}},
                                {364, {"NETZWEIGLIS_S_PSM", {}}},
                                {365, {"NETWICHT_D_PSM", {}}},
                                {366, {"NETAWICHT_D_PSM", {}}},
                                {367, {"TOPMEL_N_PSM", {}}},
                                {368, {"TOPGEN_DIFF_PSM", {}}},
                                {369, {"HSTPVSTO_PSM", {"HST_PV_STOER"}}},
                                {370, {"TSTAT_BB_PSM", {"TSTPSM"}}},
                                {498, {"TSTSAM_BB_PSM", {"TSTPSM"}}},
                                {128, {"MAX_TST_BB_PSM", {}}},
                                {626, {"VERB_PSM", {"VERBPSM"}}},
                                {627, {"VERBSAM_PSM", {"VERB_SAMMELSTOER","HST_SAMMELSTOER"}}},
                                {628, {"TOPARMATUR_SR_PSM", {}}},
                                {629, {"TOPARMATUR_S_PSM", {}}},
                                {630, {"TOPARMATUR_D_PSM", {}}},
                                {631, {"TOPPVARMATUR_S_PSM", {}}},
                                {632, {"TOP_TMPFEHLERORT_PSM", {}}},
                                {633, {"SFLISTE_PSM", {"SFOLGE_OR"}}}, //??
                                {634, {"SYSTEMPVINFO_PSM", {"SYSPVINFOPSM"}}},
                                {635, {"AMETEXTME_PSM", {"AMETEXTMEPSM"}}},
                                {636, {"SIM_BOTRETT_BUF", {}}},
                                {638, {"SIM_P40MSYMB_PSM", {}}},
                                {639, {"SIM_PROVERDS_PSM", {}}},
                                {640, {"SIM_PROVERDS_ONL_PSM", {}}},
                                {641, {"SIM_SYS_PSM", {}}},
                                {642, {"SIM_ERGDAT_PSM", {}}},
                                {643, {"SIM_BTB_PSM", {}}},
                                {644, {"SIM_BTB_LISTE_PSM", {}}},
                                {645, {"SIM_DTG_RING_PSM", {}}},
                                {646, {"STAT_BB_PSM", {"TSTPSM"}}},
                                {774, {"STAT_SAM_BB_PSM", {"TSTPSM"}}},
                                {902, {"ROHRABS_PSM", {"ROHRABSPSM"}}},
                                {903, {"SIM_ROHRABS_PSM", {}}},
                                {904, {"VSFLD_PSM", {"SATZNR"}}},
                                {905, {"SIM_AMEFLD_PSM", {}}},
                                {906, {"SIM_AMWFLD_PSM", {}}},
                                {907, {"SIM_AZWFLD_PSM", {}}},
                                {908, {"ROHRABSDAT_PSM", {"ROHRABS"}}},
                                {909, {"AMELDDIAPRF_PSM", {"PRF_AMEPSM"}}},
                                {910, {"AMESSDIAPRF_PSM", {"PRF_AMWPSM","AMWPSM"}}},
                                {911, {"AZAELDIAPRF_PSM", {"PRF_AZWPSM","AZWPSM"}}},
                                {912, {"ZW2MW_PSM", {"ZW2MWPSM"}}},
                                {913, {"TOPGEN_CHANGED_MRIDS_PSM", {}}},
                                {914, {"TOPGEN_CHANGED_MRIDS_INFO", {}}},
                                {915, {"SIM_VSFLD_PSM", {}}},
                                {916, {"SIM_LASFLD_PSM", {}}},
                                {917, {"ERGRTF_PSM", {"ERG_RTF_RING"}}},
                                {918, {"PROGAUFT_MAP_PSM", {"PROGAUFT_MAP"}}}, // Is not typed?
                                {919, {"ESPMN_TRAFOVW_PSM", {"EINSPMAN_REDLVL_ADMVAL_WATCHDAT"}}},
                                {920, {"WFCO_WPA_PV_PSM", {"WPA_PV_t"}}},
                                {921, {"TOPELEM_SX_PSM", {}}},
                                {922, {"TOPELEM_SRX_PSM", {}}},
                                {923, {"TOPMEL_SX_PSM", {}}},
                                {924, {"TOPMEL_SRX_PSM", {}}},
                                {925, {"TOPAMEL_SRX_PSM", {}}},
                                {926, {"TOPVERSORG_SX_PSM", {}}},
                                {927, {"TOPVERSORG_SRX_PSM", {}}},
                                {928, {"TOPLAST_SX_PSM", {}}},
                                {929, {"TOPLAST_SRX_PSM", {}}},
                                {930, {"TOPTRAFO_SX_PSM", {}}},
                                {931, {"TOPTRAFO_SRX_PSM", {}}},
                                {932, {"TOPLAST_DX_PSM", {}}},
                                {933, {"TOPVERSORG_DX_PSM", {}}},
                                {934, {"ESPMN_GENPVS_PSM", {"EINSPMAN_VERSORGER_PVS_CACHE"}}},
                                {935, {"TOPVERSORG_AV_PSM", {}}},
                                {936, {"TOPLAST_AV_PSM", {}}},
                                {937, {"NETM_RESULT_PSM", {}}},
                                {938, {"TP_UNBLOCKED_PVS_PSM", {"THIRD_PARTY_UNBLOCKED_PV_SHM"}}},
                                {940, {"MELD_ASTIME_PSM", {"ME_ASTIME_PSM"}}},
                                {941, {"MESS_ASTIME_PSM", {"MW_ASTIME_PSM"}}},
                                {942, {"SOLL_ASTIME_PSM", {"SW_ASTIME_PSM"}}},
                                {943, {"ZAEL_ASTIME_PSM", {"ZW_ASTIME_PSM"}}},
                                {944, {"AMESS_ASTIME_PSM", {"AMW_ASTIME_PSM"}}},
                                {945, {"AMELD_ASTIME_PSM", {"AME_ASTIME_PSM"}}},
                                {946, {"AZAEL_ASTIME_PSM", {"AZW_ASTIME_PSM"}}},
                                {947, {"TRAFO_ASTIME_PSM", {"TRS_ASTIME_PSM"}}}};

public:
  PrinssharedmemoryusageCheck(StringRef Name, ClangTidyContext *Context)
      : ClangTidyCheck(Name, Context) {}
  void registerMatchers(ast_matchers::MatchFinder *Finder) override;
  void check(const ast_matchers::MatchFinder::MatchResult &Result) override;
}; // namespace btc

} // namespace btc
} // namespace tidy
} // namespace clang

#endif // LLVM_CLANG_TOOLS_EXTRA_CLANG_TIDY_BTC_PRINSSHAREDMEMORYUSAGECHECK_H
